#默认主配置，每个环境都加载
dubbo:
  application:
    name: online-school-restful #应用名称
server:
  port: 9000
  context-path: /sys
spring: 
  profiles: 
#    active: product #生产环境
    active: test #测试环境

logging:
  path: /app/gomeo2o/logs/${dubbo.application.name} #输出到磁盘目录
  
